### ISSUE TITLE
About bilibili json api limitation

### ISSUE THREAD

**Issue by simon300000** [Jannchie/biliob-spider#22]
I also write bilibili user tracker, use api.bilibili.com and api.live.bilibili.com.

I found there is a limitation about 6 req/sec, and I got banned by 15 minutes if excess.
Do you have any idea or suggestions about how to deal with this?
Only solution I have is use proxies

**Comment by Jannchie** [comment]
Use IP pools to avoid being banned. But it seems illegal, be carefully.
